### ISSUE TITLE
Research question bank usage across moodle sites

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-MDL-70329#1]
A bit of background.

The following function makes new question_categories, which are in its essence, a question bank.
https://github.com/catalyst/moodle-MDL-70329/blob/fc335f5ea0416a729af34f00bb4a8e1fbb287e54/lib/questionlib.php#L1307-L1314
If a Moodle with one category, course and quiz existed and the individual were to edit a question bank in the quiz, the following question_categories would be created. Two for the System context, two for the category which contains the course, two for the course and two for the quiz. Each of the pairs share the same contextid. The contextid here is the bank, so four banks are created in the database but are empty. Only row in each pair will have contexts associated.

To accurately determine the number of question banks in the system we would want to be counting the distinct contextids that have questions associated with them.

```
-- Select from {question}, all the questions joining on the {question_categories} and {context}.
-- Find the distinct context id's, which would be the question banks that exist.

SELECT ctx.contextlevel, 
       COUNT(DISTINCT qc.contextid)
FROM mdl_question q
JOIN mdl_question_categories qc ON qc.id = q.category
JOIN mdl_context ctx ON ctx.id = qc.contextid
GROUP BY ctx.contextlevel
ORDER BY ctx.contextlevel;
```

A slightly faster query
```
WITH ctxid AS
 (SELECT DISTINCT qc.contextid
  FROM mdl_question q
  JOIN mdl_question_categories qc ON qc.id = q.category)
SELECT ctx.contextlevel, 
       COUNT(ctxid.contextid)
FROM mdl_context ctx, 
     ctxid
WHERE ctx.id = ctxid.contextid
GROUP BY ctx.contextlevel
ORDER BY ctx.contextlevel;
```

**Comment by mattporritt** [comment]
For context as the proposed project converts existing site, category, and course level question banks into courses with discrete question bank activities; we want to know the "burden" this would be put on existing sites and how many of these new course instances would be created.

**Comment by mattporritt** [comment]
Using the sql query designed in previous comments we ran it across the fleet of client Moodles. The result was the scatter plot below.

![image](https://user-images.githubusercontent.com/7369127/114804861-5b506880-9de5-11eb-989a-81dc2332dd56.png)

As expected all sites only have one system level question bank.
On average sites have 50 Category level question banks, which means 50 new courses with question bank activities per site will be created as part of the Quiz 4.0 upgrade process.
Apart from a few outliers, on average Moodle sites have 500 course level question banks. This means that existing sites will get a new question bank activity created in 500 courses as part of the Quiz 4.0 upgrade process.

**Comment by mattporritt** [comment]
Based on the initial findings. The approach of converting category and site level question banks with courses will continue.
