### ISSUE TITLE
mod_qbank: view_hidden capability (plus others)

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#100]
We need a capability that can be assigned to users to allow them to view and use a hidden question bank.
By use I mean add questions from a question bank to a quiz that is hidden. Also to allow editing and adding questions to a question bank that is hidden.  

By hidden I mean, actually hidden or made unavailable by some availability condition

The above may be in reality multiple capabilities

Also see issue #24 for more background

**Comment by guillogo** [comment]
Hi @mattporritt ,

The first thing done about capabilities was: not allow the student and guess role to view mod_qbank. https://github.com/catalyst/moodle-MDL-70329/pull/118

TODO: create new capability viewhidden mod_qbank.

Thank you.

**Comment by mattporritt** [comment]
PR #118 was approved and merged

**Comment by guillogo** [comment]
Hi @mattporritt 

This will be the new capability to see hidden qbank modules: https://github.com/catalyst/moodle-MDL-70329/pull/126

Thank you.

**Comment by mattporritt** [comment]
@guillogo PR #126 approved and merged
