### ISSUE TITLE
Bulk action UI

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#121]
In Moodle 4.0 contributors will be able to write their own qbank_* plugins that extend the question bank functionality. One of the types of functionality that can be developed is "bulk actions". These are actions that operate on multiple questions at once.
Current core bulk action include:
* Deleting questions
* Moving questions

A future bulk action may be for example:
* Bulk tagging of questions.

Each of these actions can have different workflows to do what they need to.  Some may require multiple user input steps.
We need to come up with a UI and underlying code that will suit these different bulk workflows.

The current wire frames reflect existing Moodle functionality where the exisitng bulk action UI elements are "fixed":
![bulk actions wireframe](https://user-images.githubusercontent.com/7369127/120257921-7d8a4100-c2d4-11eb-8aa7-be9ab3251cc9.png)

Instead of this an alternative approach could be one where:
1.  A user selects the questions that they want to perform a bulk action on
2. The user then selects the bulk action they wish to perform from a select menu
3. Upon selection the workflow for that particular bulk action (as directed by the plugin) starts

Mock up screen shot below:
![bulk actions suggest](https://user-images.githubusercontent.com/7369127/120258194-e8d41300-c2d4-11eb-96af-a90038dce492.png)

Currently this relates to issue: #87 and #88

**Comment by mattporritt** [comment]
We need to discuss this approach with the broader team

**Comment by abonaccorso** [comment]
@mattporritt I like your wireframe for future bulk actions and the idea behind. 

Another future bulk functionality I could think of could be

- bulk export questions

**Comment by mattporritt** [comment]
As discussed in the project meeting we'll go ahead with the proposal to:

**Comment by abonaccorso** [comment]
@mattporritt thanks for answering my general question on the place of the bulk action drop down. That sounds sensible to me.
