### ISSUE TITLE
Project document access to additional developer resources

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#13]
Grant access to project documentation to additional Catalyst Developers

**Comment by mattporritt** [comment]
The first step here is to confirm the new developers to work on the project

**Comment by mattporritt** [comment]
I've reached out via email to get the new developers access granted

**Comment by abonaccorso** [comment]
access granted

**Comment by mattporritt** [comment]
Confirmed, both @safatshahin and @guillogo have access
