### ISSUE TITLE
qbank_editquestion - enhance qtype edit form

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#149]
Enhance the editquesiton form from the core_question to include the following information:
Version information
Created by
Modified by
Number of times used
Facility index
Discrimination index

-- all those information should come from the associated plugin, the idea should be to have a public api from those plugin to access those information

**Comment by safatshahin** [comment]
Hi @mattporritt 
According to the wireframe:
![Screenshot 2021-06-09 11:37:29](https://user-images.githubusercontent.com/55496911/121279002-1cd3b780-c917-11eb-8fc7-557e7979ecd6.png)

It shows who created and who updated in the version control section, but this information is already available in the page here:
![Screenshot 2021-06-09 11:39:15](https://user-images.githubusercontent.com/55496911/121279088-51e00a00-c917-11eb-95b0-f1e63545ddee.png)


Does that mean the current one should be removed?
Thanks

**Comment by mattporritt** [comment]
@safatshahin yes I think we should remove the current one and replace it with this.
I'm also thinking that maybe we should start with this new form section "collapsed" . I can see it having a lot of information that can take up space, that while useful you may not want to see when quickly creating a section.

**Comment by abonaccorso** [comment]
@mattporritt and @safatshahin, yes we can definitely remove the current "Created/last saved"-section. If I remember correctly @lucaboesch and I discussed that we might show only parts of the information in "authors, version control and usage" at the start and others "collapsed". But I do not remember, if we took a decision. Do you @lucaboesch?
