### ISSUE TITLE
Restore of pre 4.0 courses and activities

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#15]
When a course from a pre 4.0 Moodle is restored into a 4.0 Moodle. The course level question bank will need to be converted into a new mod_qbank instance for the course.

This will be the same core logic that will be used for #11

**Comment by safatshahin** [comment]
Hi @mattporritt 
Should it be done as a new tracker or a part of 71378? as of my understanding, it will require changes core_backup and need to be done after the changes in 71378 are integrated in core.

**Comment by guillogo** [comment]
Hi, after integrating this PR https://github.com/catalyst/moodle-MDL-70329/pull/218 to the mod_qbank API this issue can start. Moving this to Ready for Development. Thank you.
