### ISSUE TITLE
Implement question status

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#153]
Implement question status, this implementation will require changes to the following:
a qbank_questionstatus plugin to show the status of the question
changes to the db layer to have the status of a question, probably a flag value determining the status
changes to the mod_quiz to use only active questions
changes to the qtype form to have this dropdown as an option
some logics around different question status

@mattporritt  can you please direct me to any additional information about this feature and also let me know if i missed something in the list, thanks

**Comment by abonaccorso** [comment]
There are still some open questions on the status of a question @safatshahin. But you may find further information on page 6 of this document under the title "Creating questions using drafts" (https://docs.google.com/document/d/1JPBTqpCbtdRFTJuX-GIaxKyxtFLoUdPO/edit#heading=h.87lo6i664bs1). There are some further tought here: https://docs.google.com/document/d/1KLzA4BsktPLMIls83rCK13ia6Z9KLeP8/edit. The first scenario is not yet decided on, however.

I am not sure what you mean by "active" questions. If you refer to "achived" questions (that can be reactivated): personally I always saw them as part of this status - but I do not know what @timhunt thinks about this. And as I am thinking mostly from a users perspective, maybe @timhunt can add some sensible information from a developers point of view?

**Comment by mattporritt** [comment]
Hi @abonaccorso ,
In this context "active" means the same as "final" in the user stories doc. Which is the opposite of draft.

**Comment by mattporritt** [comment]
Also by looking at the docs, each version of a question can have three different states:
* draft - I'm still working on this 
* final - this version is done and OK to use
* hidden - this version is hidden, it can't be changed but I don't want people to see it.

How we actually implement these still is a bit unclear. For example: If a question is shared with me, am I going to be forced to not be able to use any versions of it in draft.

**Comment by abonaccorso** [comment]
Hi @mattporritt thanks for clarifying regarding "active" and "final". Make completely sense to me.

Regarding the three statuses I agree: it is still unclear how to implement this. Tim, Luca and I once started discussing but then someone went on holidays... 

I am not sure if "archived" could also be a status? Just asking because from my point of view, this would make sense - but it might be complete nonsense from a developers point of view.

**Comment by abonaccorso** [comment]
@safatshahin I am confused that this issues is closed. The question regarding what statuses there are is still open. And I cannot see any changes regarding statuses on the test site.

**Comment by safatshahin** [comment]
Hi @abonaccorso 
My sincere apologies for the confusion. I used this issue to implement the initial backend implementation of status, which is ready and draft (hidden is already there), and also made a column to show the status. We haven't pushed the versioning changes yet. We have planned to make a major push tomorrow with all the versioning changes done so far. Please let me know if you want to keep this issue open.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin no worries! Ok, I understood. So we can keep it closed. I will delete the question tag - but keep the question on my to do list, so we don't forget.
