### ISSUE TITLE
mod_qbank: Add to section 0

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#159]
When a mod_qbank instance is created as part of the migration/upgrade to Moodle 4.0 the instance should be added to section 0 of the course it is in

**Comment by guillogo** [comment]
Hi @mattporritt 

The requirement was done already here: https://github.com/catalyst/moodle-MDL-70329/blob/master_MDL-71378/mod/qbank/classes/helper.php#L184

Closing this issue now.

Thank you.
