### ISSUE TITLE
Mod Qbank Icon

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#16]
We're making a new activity type so it needs a new icon :)

The Moodle guide around icons is here: https://docs.moodle.org/dev/Moodle_icons#Activity_icons

People are most likely going to have opinions on this so lets start with something to just "get it out there", and we can iterate from there

**Comment by mattporritt** [comment]
@meepster-nz over to you on this

**Comment by lucaboesch** [comment]
We've heard from people with design skills.
 Should we try to reach out if they want to create an intermedial initial one?

**Comment by mattporritt** [comment]
Hi @lucaboesch ,
I'm happy for anyone to volunteer and make an icon. It would be good to have some choice.
In the mean time I'll upload the initial logos we've come up with.

Cheers,
Matt P

**Comment by mattporritt** [comment]
Here are the icons we've come up with initially. It is difficult to come up with activity icons that look ok at both 24 and the smaller 16px size. There are two variants.

![questionbank-24px](https://user-images.githubusercontent.com/7369127/115482316-bffe3e00-a291-11eb-9384-cba5eddc0051.png)
![questionbank-16px](https://user-images.githubusercontent.com/7369127/115482319-c12f6b00-a291-11eb-8575-c912b07e7337.png)
![questionbank-wheel-24px](https://user-images.githubusercontent.com/7369127/115482320-c1c80180-a291-11eb-813e-0b0a8cbbca3d.png)
![questionbank-wheel-16px](https://user-images.githubusercontent.com/7369127/115482321-c2609800-a291-11eb-9af2-e43a87d609c8.png)

[qbank_icons.zip](https://github.com/catalyst/moodle-MDL-70329/files/6347404/qbank_icons.zip)

**Comment by mattporritt** [comment]
I'll seek some team feedback on this, but for the time being we'll just pick one to go with the in progress code

**Comment by mattporritt** [comment]
For reference this is how the icon looks in the activity edit screen and activity chooser
![Screenshot_2021-04-23 Editing Question Bank](https://user-images.githubusercontent.com/7369127/115801992-60369d00-a421-11eb-8b2d-ffbf7a71b095.png)
![Screenshot_2021-04-23 Course test course](https://user-images.githubusercontent.com/7369127/115801994-62006080-a421-11eb-95cb-5041042acb01.png)

**Comment by abonaccorso** [comment]
Here are some sketches drawn by Yvonne Wolf
![grafik](https://user-images.githubusercontent.com/13217187/116223670-0d762180-a750-11eb-88ca-134fd249c3d7.png)

**Comment by abonaccorso** [comment]
@mattporritt I sent Yvonne the guidelines you added above. Where can she hand in the icon once it is ready?

**Comment by mattporritt** [comment]
@abonaccorso Adding the icon here as a zipped SVG might be the easiest. 
Otherwise submitting it as a pull request against master_MDL-71378 and we can merge it in.

**Comment by abonaccorso** [comment]
thanks @mattporritt I will let Yvonne know

**Comment by mattporritt** [comment]
Current icon revisions. 
![new_icons](https://user-images.githubusercontent.com/7369127/120727997-49569080-c51f-11eb-90e7-6065a6f681f9.jpg)
The current icon we are using in mod_qbank from the above set.
![intermediate_icon](https://user-images.githubusercontent.com/7369127/120728022-56737f80-c51f-11eb-856b-f16f6415cfda.jpg)

**Comment by mattporritt** [comment]
The intermediate icon has been deployed to the test site

**Comment by mattporritt** [comment]
Moving this one to done, the final icon (below) has been chosen and added to the code base

![image](https://user-images.githubusercontent.com/7369127/124203531-4354cf00-db20-11eb-97bb-29b3e71af7c9.png)
