### ISSUE TITLE
Navigation: Question bank administration menu list link

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#160]
As part of the changes to Moodle the link to the "Question bank" that is accessible from the course administration window (see screen shot) that now goes to the course level question bank. Should go to a summary lists of all question bank in this course, including question banks in activities.

TBD: the layout and information displayed

![image](https://user-images.githubusercontent.com/7369127/121624618-327ee380-cab5-11eb-9f72-7bc41bd5a2df.png)

**Comment by mattporritt** [comment]
HI @timhunt @lucaboesch and @abonaccorso
We talked about this behavior in our catch up meeting. I just want to make sure I captured things correctly?

We can decide how the information for the question banks is displayed later, for now I just want to make sure the idea was correct.

**Comment by timhunt** [comment]
Yes. I think we replace Question bank and the four sub-items with a single 'Question banks' link, and I think a good enough first implementation is just to link to mod/qbank/index.php?id=[courseid].

(What should happen if the course does not have question banks yet? My feeling is that the link should still exist, and if there are no qbanks in the current course, that index.php should display a paragraph of text which tells people how to start using question bank (do add activity, with a link to the docs.)

**Comment by abonaccorso** [comment]
@mattporritt I can confirm that you captured the discussion. And I agree on @timhunt's sugestion to add a description and link to the Moodle docs it there exists no question bank in the course.

**Comment by guillogo** [comment]
HI @safatshahin 

I've added the new node in the course admin page. This is the PR: https://github.com/catalyst/moodle-MDL-70329/pull/167

It'll add a link to the mod/qbank/index page.

Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo 
PR merged
thank you
