### ISSUE TITLE
Question bank lang string change

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#162]
@lucaboesch Was nice enough to make a PR for the lang string changes we discussed for the question banks admin menu.

The PR and commit are here: https://github.com/catalyst/moodle-MDL-70329/pull/140/commits/1a13a69872a50a6c9ecc6cde306ff61184431d1a

Making this issue to go along with it so it doesn't get missed.  
We can either cherry pick the change in, or get Luca to rebase against correct branch etc.  Either way will preserve his authorship

**Comment by safatshahin** [comment]
Added the commit in the base 71516
