### ISSUE TITLE
mod_qbank: remove completion support form 

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#18]
It doesn't make sense for mod_qbank to support completion tracking, as students can't complete it.
Remove support for the completion api from the mod_qbank activity.

Likely a good example to follow here is mod_label

**Comment by abonaccorso** [comment]
I completely agree on that point! And I think it would also be sensible to remove the point "availability" under "common module settings" because students won't be able to use the question bank so it makes no sense to make it visible to them.

**Comment by mattporritt** [comment]
I've split this out the availability into a separate issue as I'm not sure if this can be excluded easily. It might need more investigation

**Comment by guillogo** [comment]
Hi @safatshahin 

Thank you for working on this one, could you have a look to this 3 points please?:

1. Can you please take a look to this documentation about Code Style in the comments: https://docs.moodle.org/dev/Coding_style#Documentation_and_comments 
2. I've added a couple of comments in the commit.
3. I'm getting this warning when try to add new qbank activity:

```
Did you remember to call setType() for 'visible'? Defaulting to PARAM_RAW cleaning.
line 1452 of /lib/formslib.php: call to debugging()
line 322 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 228 of /lib/formslib.php: call to moodleform->_process_submission()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 150 of /course/modedit.php: call to moodleform_mod->__construct()
Did you remember to call setType() for 'availabilityconditionsjson'? Defaulting to PARAM_RAW cleaning.
line 1452 of /lib/formslib.php: call to debugging()
line 322 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 228 of /lib/formslib.php: call to moodleform->_process_submission()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 150 of /course/modedit.php: call to moodleform_mod->__construct()
```

@matt-catalyst Can we also remove Competencies from the form? (as students won't be able to use the question bank)

Thank you.

**Comment by matt-catalyst** [comment]
I think the above question was for @mattporritt, not me.

**Comment by mattporritt** [comment]
@guillogo adn @safatshahin yes to removing competencies as well

**Comment by safatshahin** [comment]
Hi @guillogo 
Thank you for reviewing and pointing out those in the commit, really helpful. Please review the latest commit, I have made changes according to your comment and also removed support for competency.

**Comment by mattporritt** [comment]
This has been removed and merged. Closing
