### ISSUE TITLE
Rename branches

### ISSUE THREAD

**Issue by guillogo** [catalyst/moodle-MDL-70329#184]
Hi, We want to rename the branches to make them more understandable to external users.

E.g: 

Before: master_MDL-71378
After: master_MDL-71378-mod_qbank

Before: master_MDL-71585
After: master_MDL-71585-qbank_managecategories

**Comment by guillogo** [comment]
Created branch: https://github.com/catalyst/moodle-MDL-70329/commits/master_MDL-71378-mod_qbank

TODO: 

1. Update `Pull Master Branch` and `Pull Master Diff URL:` in tracker https://tracker.moodle.org/browse/MDL-71378 
2. Use this branch in the test sites.

**Comment by guillogo** [comment]
Branch master_MDL-71769 replaced: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71769-module_control_feature

**Comment by safatshahin** [comment]
This task is done for all the plugins, closing now.
