### ISSUE TITLE
Question bank classes from config

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#187]
Currently, question bank allows a defined set of classes set from the config, as the features didn't have the ability to be enabled or disabled, this config used to give the ability to use certain classes in the view, for example:

$CFG->questionbankcolumns = ['edit_action_column', 'preview_action_column'];

This will show only those two columns in the view.

Now with the changes, columns are implemented as a qbank plugin. Now my question is, should we remove this feature? as plugins will have to enable/disable for the view, or keep supporting it by pointing them to the plugin in the background (which might be a bit tricky).
If we remove this config, do we need any mechanism to identify those configs and enable only those plugins to have zero effect on sites using this config?

@mattporritt @lucaboesch @timhunt

**Comment by timhunt** [comment]
We should remove it - and make sure this is clearly highlighed in the release notes - but that is all we should do.

$CFG->questionbankcolumns was implemented becasue it was better than nothing. However, having used it to customised the question bank on our Moodle site, my findings was that it was only a very small amount better than nothing (it was a serious pain, and dangerous when things changed in core.) So, good riddance!

**Comment by safatshahin** [comment]
Thank you for the clarification @timhunt 
Will implement this in the class renaming tracker.
Thanks.
