### ISSUE TITLE
questiontypebase - make changes for question version

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#189]
create new question is currently handled by questiontypebase in the save_question() function: 364, where the qtype plugins do the logic needed to be done as a new record insert and calls the parent which inserts the question record: 490, this base is relying on only the question table atm, which needs to be changed to insert the data on three of the tables for versioning. 

Possible changes to:
save_question()
delete_question()
....and maybe some more.
in save_question():490, its giving every question a hash in the version field, this need to be changed as well.

will discuss the question file area with different version of questions in a different github issue as a q/a, might need to address that in a different issue if required.

**Comment by guillogo** [comment]
Hi @safatshahin, this is the PR with the changes in to add the records in the new tables: https://github.com/catalyst/moodle-MDL-70329/pull/248

Also, there are basically 2 TODO things in other trackers:

1. mod_quiz: edit the function `quiz_add_quiz_question` in localib.php to save a reference record when a question is added to a quiz from the question bank.
2. Change status field in version, this should be done in question/local/view.php in the deletequestion plugin.

Thank you.

**Comment by guillogo** [comment]
Hi @safatshahin 

An overview of the changes:

**1. Save and update**
When a question is created:
- A question record is created
- A question_version record is created (by default for now the status is 0 - Production)
- A question_bank_entry record is created
- A question_references is created

When a question is edited and the status is hidden or production:
- A question record is created
- A question_version record is created
- A question_references is created

When a question is edited and the status is draft:
- The same question record is updated
- The same question_bank_entry record is updated

If a question is duplicated, it will work as new question.

**2. Delete**
The delete feature is manage by questionlib.php so no action required in questiontypebase.

**3. Generator**
The question creation in The test generator calls the save_question function in questiontypebase.

**4. Unit test failing**
There are unit test failing:
- Question capabilities checks - It needs changes in questionlib.php
- Privacy - It needs changes in question/classes/privacy
- Question engine - Will be manage by question/engine

Thank you.
