### ISSUE TITLE
questionlib - make changes for question version

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#191]
With the implementation of versioning in question, the biggest affected location is questionlib. This is issue will be quite big and need some deeper focus while working on it and also the resource working on this issue need to make sure that the understanding of the question version, db structure changes in question, and also the understanding of qbank API and and plugins are clear before even starting on this issue.

I am primarily putting a list of methods in the questionlib where the changes possibly need to take place, please note this is not a final list, this list is based on the primary analysis of the questionlib, please keep adding functions in the list if any of them are missed or need to be refactored instead of changing. Please also note that there will be more functions that might need to be added, which are not listed or described here but that is a part of this issue.

question_context_has_any_questions() -- record existence check might need to be changed because of the changes to the relation with question_categories and question table.

question_remove_stale_questions_from_category() -- recordset select need to changed as there is no direct co-relation between question and question_categories, need to go through version and bank_entry.

question_category_delete_safe() -- get_records:270 needs changing as the criteria won't work anymore as there is no direct connection, :282 same thing, 

question_category_in_use() -- same no direct relation

question_delete_question() -- one of the most fundamental method, :345 record SQL needs changes, :383 recursive delete need some digging with versioning

question_move_questions_to_category() -- :654 getting the question query needs to change, :666 as well

question_move_category_to_context() -- :725 and some more

question_preload_questions() --  need some close attention to this for question load

get_categories_for_contexts() -- query needs to change

question_has_capability_on() -- query needs to change

core_question_question_preview_pluginfile() -- looks like this method is not used anywhere, give it another look, either change or deprecate

please also look at other functions in the querstionlib to get a better view of changes.

@mattporritt   I have added as much as information as possible, it will be a big issue and questionlib is kinda huge, please let me know if there is anything that can be added to help this build, I figured it will be easier we don't split this issue as it's in one specific file.

**Comment by guillogo** [comment]
questionlib.php changes done in: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning
