### ISSUE TITLE
Create a mod_qbank activity skeleton

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-MDL-70329#2]
Create the base mod for the new qbank activity

**Comment by mattporritt** [comment]
This will just be the base, other functionality will come later in other issues.

**Comment by mattporritt** [comment]
@nhoobin are you able to please push the work done on this so far to a feature branch in this repository as per #12 
Cheers.

**Comment by mattporritt** [comment]
A very basic plugin skeleton has been created and pushed to the branch: master_MDL-71378
This is just the base plugin skeleton boilerplate.

We should add some basic functionality before calling this issue done. Features for the plugin will be made as individual cards

**Comment by mattporritt** [comment]
Moving this to done. The current activity allows the plugin installed in Moodle. Also for an instance of the plugin added to a course.
We'll make new issues for the individual features
