### ISSUE TITLE
mod_qbank: add icon

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#20]
The current mod_qbank activity doesn't have an icon. Lets go with the current working icon from: issue #16 

This will at least squelch the 404 errors when the activity is added to a Moodle

**Comment by guillogo** [comment]
Hi @mattporritt this is the PR for the icon https://github.com/catalyst/moodle-MDL-70329/pull/22

1. I've created the pix folder
2. Added the icon.png and icon.svg (24px)

Thank you.

**Comment by mattporritt** [comment]
PR has been merged in
