### ISSUE TITLE
qbank migration q/a

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#215]
There are two types of migration that will be required with the release of 4.0 for the question bank:
1. Migration of context and course creation - for mod_qbank
2. Migration of question and quiz tables for versioning

We need to do some technical go-through to determine if there is any dependency or one has to be done before another. If so, the whole migration for those two needs to be considered using a new approach.

This issue is created to do some discussion to document the outcome of the meeting in this issue for any future reference.

**Comment by mattporritt** [comment]
Hi @safatshahin 
From my understanding of the upgrade process (which we need to verify) the core tables etc in `lib/db/install.php` are processed first. This is where all the question tables etc are.  So based on this we will need to handle the versioning and other db changes first.
After that we can then do the install actions for mod_qbank; creating the new courses etc.

Ultimately, I think there will be several steps here. With some being done in "core" and some being done at the plugin level.
But I think at first glance we will need to do the versioning changes first.

Cheers,
Matt P

**Comment by safatshahin** [comment]
Thank you for the clarification @mattporritt 
It totally makes sense to have those versioning changes to go first and then integrating the mod_qbank. As in the project board, the initial plan was to integrate mod_qbank first which made me think about it.
Keeping this ticket open for now.
Cheers!
