### ISSUE TITLE
question versioning - make changes to qtype admin page

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#223]

**Comment by abonaccorso** [comment]
Hi @safatshahin can you specify somewhat more what changes you will make to the admin page?

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for pointing this out. With versioning, the database schema is changing for the question table and the question table is used pretty much all over the core. I have done a deep investigation of the usage or the question table in core and made issues accordingly to change that DB schema to those places. This issue is related to the qtype admin where it uses question table directly. We might change that schema there or might point to that questionlb or core_question.
I hope I made it kinda clear, apologies if the explanation is not clear enough.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin thanks for answering. It is still somewhat fuzzy (well, quite fuzzy), but so far clear as it is work on underlying structures, not something like settings an admin can change.
