### ISSUE TITLE
question versioning - make changes for calculated questiontype

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#229]

**Comment by abonaccorso** [comment]
@safatshahin can you specify on the changes being made for calculated questiontype? I think it would be good if someone from community could have look at.

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for pointing this out. The versioning will change the DB structure of the question table, and the calculated qtype is using the question table directly. I might move this to questionlib or core_question rather than letting this qtype to call the DB directly. 
The change will be entirely related to versioning and db schema changes, if anyone from the community wants to pick up this, the developer needs to go through the docs and changes for versioning, DB schema, and also the changes we are doing in questionlib and core question and also the API and then do a PR against 71696 branch.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin thanks for answering my question. Seems, my comment was unclear. With "I think it would be good if someone from community could have a look at it" I refered to UAT rather than to a developer taking over this part of work. Sorry for creating confusion on this!
