### ISSUE TITLE
question versioning - make changes to multianswer qtype

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#233]

**Comment by guillogo** [comment]
Hi @safatshahin 

I've created a PR adding the changes in qtype_multianswer to work with versioning. https://github.com/catalyst/moodle-MDL-70329/pull/256

**Step 1**
When a new question is created:
1 parent created: version 1 - question bank entry 1 - reference 1
1 child 1 created: version 1 - question bank entry 2 - reference 2
1 child 2 created: version 1 - question bank entry 3 - reference 3

**Step 2**
If question is edited and has not a draft status:
1 parent created: version 2 - question bank entry 1 - reference 4
1 child 1 created: version 2 - question bank entry 2 - reference 5
1 child 2 created: version 2 - question bank entry 3 - reference 6

**Step 3**
If question is edited and has draft status (base on **step 1**):
1 parent edited: version 1 - question bank entry 1 - reference 1
1 child 1 edited: version 1 - question bank entry 2 - reference 2
1 child 2 edited: version 1 - question bank entry 3 - reference 3

Thank you.

**Comment by abonaccorso** [comment]
Hi @guillogo if I understood today's discussion correctly, step 3 in the above scenario does not exist. Independet of the status of a question (draft or not), every edit of a question (edit meaning someone clicked the "save" button, not autosaved edits) creates a new version. So also if a question is a draft, a new edit creates a new version.

**Comment by guillogo** [comment]
Hi @abonaccorso thank you for the comment, that's correct. The changes were done just before the meeting, now I'll adjust the questiontype base and the question type plugins in order to work with the behaviour expected. Thank you.

**Comment by guillogo** [comment]
Hi @safatshahin this is the PR https://github.com/catalyst/moodle-MDL-70329/pull/262 after the changes discussed in the meeting and is also rebased against versioning branch. Thank you.
