### ISSUE TITLE
question versioning - question deletion

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#234]
This is discusstion around deletion of question for versioning implementation:

1. Question deletion - matt had a really good idea of removing the just the reference to a question while a question is deleted rather than deleting the actual question. Which is possible using the db structure for versioning. the question_references table will add a reference entry whenever a question is added to a quiz or any other plugin implementing question bank. Now my idea is, everytime a question is created in a question bank, it also adds a referece to the same question having the component -> core_question, questionarea -> qbank, itemid -> questionid. Now when a question is deleted, rather than deleting the question, it will delete the reference in the table and the question will be kept as it is. There will be a scheduled task which will clean up this data time to time. Does this approach sound alright?
G: Sounds right to me, and the task also seems the right aproach (agreed)
MP: yes, that's how I thought it'd work.

1. If point 1 is alright, does that mean, users will be able to delete question in use? or its just for question sharing? If users can delete question in use like used in quiz, i think it will become confusing when it comes to editing a quiz question or in case question is deleted by accident.
G: I think if a question is deleted by a user (reference removed) from his side and is used in a quiz  it will still have the reference to the quiz so the task wont delete the question.
S: ok that means if a question is deleted from a bank. that will only be edited from the quiz.
MP: This is all correct. I think this becomes easier to implement (and hopefully to understand), if we treat question versions as immutable. So when you edit a question, it ALWAYS makes a new version of the question.
So a question could be used in 10 places in Moodle. Which means there will be 10 references to the question in the database.  The question can be edited from any of those ten places,  Then whoever edits it just makes a new version of the question. but this won't effect any of the versions used elsewhere. Same as if one of those instances are deleted.

As these two points seems correct, then there are these two are needed to be implemented:
1. With the migration, question_references table need to reference the question itself in the table for all the available questions in the migration.
2. The question_bank_entry has a hidden column, which wont be necessary as users will be able to delete questions even if they're in use and cleanup will be done via a scheduled task. If that's the case, the db schema and the migration will need changes for that as well. 
3. In case we want to keep the hidden value somewhere, I believe it should be in the question_version table as quiz will use specific version of a question and some versions might need to be hidden and some might not, it should not be in question bank entry as hiding the entry means all the versions are hidden.

@mattporritt @guillogo Any thoughts on this?

**Comment by mattporritt** [comment]
Hi @safatshahin ,
With regard to hiding I think this should be done at a per version level. So some versions of a question can be hidden. Being able to hide question versions is mentioned in the user story docs: https://docs.google.com/document/d/1JPBTqpCbtdRFTJuX-GIaxKyxtFLoUdPO/edit#heading=h.87lo6i664bs1 and https://docs.google.com/document/d/1KLzA4BsktPLMIls83rCK13ia6Z9KLeP8/edit

**Comment by safatshahin** [comment]
Hi @mattporritt 
Thanks for the clarification, so the db schema needs to be changed as per those 1, 2 and 3 mentioned above.

**Comment by mattporritt** [comment]
Yes

**Comment by safatshahin** [comment]
Documented here:
https://docs.google.com/document/d/1LjxpSjYA_lo6psPClp60zngaZmmESF7bVnUDHE6Vrf8/edit#heading=h.9xlyl2mf5l5p

Created this issue to proceed with the code changes:
https://github.com/catalyst/moodle-MDL-70329/issues/235

**Comment by abonaccorso** [comment]
please note that the final decision on how "hiding" of questions/question versions should work is still to be taken.

**Comment by safatshahin** [comment]
Note: need to make changes to deletequestion plugin as a part of this issue.

**Comment by safatshahin** [comment]
These matters are discussed and technical decissions are made. Delete question plugin changes are done. Closing this issue.
