### ISSUE TITLE
question versioning db schema - change for deletion

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#235]
According to this document:
https://docs.google.com/document/d/1LjxpSjYA_lo6psPClp60zngaZmmESF7bVnUDHE6Vrf8/edit#heading=h.9xlyl2mf5l5p

1. Changes needed for the reference table in the migration
2. Changes for entry table in install and upgrade
3. Changes to version table in install and ugprade
4. At the moment we have hidden as 1 when its hidden.
With migration, this value should go to status field in version table. (G: Agreed)
Now, whenever there is hidden = 1, migrate it to status = 1
whenever there is hidden = 0 migration it to status = 0
the status = 2 will be left for draft
1 -> hidden
2 -> draft
0 -> published
5. Migration for random questions to set_reference table

Following this issue for detailed info: https://github.com/catalyst/moodle-MDL-70329/issues/234

**Comment by guillogo** [comment]
Hi @safatshahin 

Just to confirm, the point 1 -> set_reference should have a reference to questionid in the version table instead of the versionnumber per se (Is missing in the the new diagram from the doc)?

Points 2 to 4 are done here: https://github.com/catalyst/moodle-MDL-70329/compare/master_MDL-71696...master_MDL-71696-235

Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo 
I think it should be version id as a reference seems to be connected to a version of the question, you mean the itemid field right?

**Comment by guillogo** [comment]
HI @safatshahin 

This is the PR with the changes required for versioning and after our meeting: https://github.com/catalyst/moodle-MDL-70329/pull/240

Thank you.

**Comment by guillogo** [comment]
Hi The changes have been merged and squashed in the base branch: https://github.com/catalyst/moodle-MDL-70329/commits/master_MDL-71696 thank you.
