### ISSUE TITLE
If quiz is deleted, questions in quiz level question bank are not deleted but moved

### ISSUE THREAD

**Issue by abonaccorso** [catalyst/moodle-MDL-70329#241]
If a create a quiz an directly add some questions, I would expect, that those questions are deleted together with the quiz level question bank once I delete the quiz. But the questions are moved to another category. I suppose, this is due to the qbank not yet being fully refactored.

**How to reproduce**
1. Create a quiz
2. Add a question via "add a question" to the default category for this quiz (so it is stored in quiz level question bank)
3. Delete the quiz
4. Have a look at the question bank (course administration > question bank > click one of the question banks of the course)
5. Browse the categories: You will find the questions of the deleted quiz as subcategory of one of the question banks (activities)

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for reporting this issue.
I have done some deep debugging around this issue and found some very interesting bits. This is an existing issue from the current master branch and the location it touches for this issue, we didn't make any changes for the API refactoring and also the changes for versioning are close to the current code which makes to functional changes.
There are a couple of points I need to discuss with @timhunt for some advice around this implementation.
I will keep you posted.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin that's fine with me

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for creating the issue. The fix has been implemented and pushed to the testsite. Please have a look now and let me know if you have any other issues.
Cheers!
