### ISSUE TITLE
comments entered via comment window are not visible in preview and vice versa

### ISSUE THREAD

**Issue by abonaccorso** [catalyst/moodle-MDL-70329#245]
**Current behaviour**
If I enter a comment in the question preview and save it, the counter in the column "comments" in the question list is raised by one. But when I click on the counter, I cannot see the comment that I had previously added in the question preview. 

**Expected behaviour**
I should see comments in the question preview and when clicking on the counter in the comments column in the question list, independet on where the comments had been entered.

**How to reproduce**
1. Create a question bank
2. Add a question
3. open the question preview
4. add a comment
5. close the question preview --> you are back in the question bank and the counter in the column "comments" says "1"
6. click on the counter in the column "comments" --> you won't see the comment you previously added in the question preview (step 4).
7. add a comment
8. close the comment window --> you are back in the question bank and the counter in the column "comments" says "2"
9. open the question preview --> you won't see the comment you previously added in the via comment window (step 7)

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for your information about the issue. I have investigated the following the steps, unfortunately, can not replicate them. Can you please have another look and let me know if the issue still persists?
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin I was not even aware the issue was still open. I tested aroung 2 weeks ago and it was already working - so I expected you fixed it. Sorry for that!
