### ISSUE TITLE
comments window should be "closed", not "cancel"

### ISSUE THREAD

**Issue by abonaccorso** [catalyst/moodle-MDL-70329#246]
When I want to add a comment to a question in the question bank by clicking on the counter in the column "comment", a separate window opens. To close this window, there is a button, that says "cancel". I think it would be better if the column would say "close"

![grafik](https://user-images.githubusercontent.com/13217187/127995166-bb1e46a5-a141-4b4e-81e1-c5d0e0c965fb.png)

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for informing. This has been resolved with the comment plugin release. 
Thanks.

**Comment by abonaccorso** [comment]
Hi @safatshahin I have seen this - and forgotten to close the issue. Sorry!
