### ISSUE TITLE
Create tasks: Scenario, Filter 1

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#27]
Split the following user story is to project tasks:
**Filter 1: Adding questions from question bank using filters**
Exam coordinator Eva is putting together the exam today. She first creates the quiz and sets the quiz settings as needed. She then starts adding questions via “add question from question bank”. For each topic taught in the course Eva has defined several learning objectives that need to be covered. This information has been attached to the question using tags. So Eva now filters her questions for the tags “topic1” and “learning objective 1.1”, “learning objective 1.2” and “learning objective 1.3”. She does not want to include questions that have been asked in the last two semesters so she adds the filter criterion “last used before 11.01.2020”. She than sorts the questions by discrimination index to make sure she does only include old questions of high quality or newly written ones. She has a closer look at certain questions, opening them in a separate browser window. Working through the questions she makes some comments in order not to forget certain thoughts. Then she decides which questions to add, checks the corresponding checkbox and adds them to the quiz. 
She then proceeds with topic 2. When she had built and loaded the filter she realises that she has forgotten one learning objective. So she adds the learning objective and updates the filter.
She then proceeds with topic 3. After having checked half of the questions she is interrupted by a meeting (she knew she had it but was so absorbed with her work that she completely forgot the time). In order not to forget where she was interrupted, she notes down the question number of the question last checked and sets a bookmark for the filter. After the meeting she accesses the filter via browser bookmarks and restarts working at the question number she noted down earlier.

**Comment by mattporritt** [comment]
Created issue #32 qbank_comment as a task from this user story

**Comment by mattporritt** [comment]
Created issue #47 qbank_filter as a task from this user story

**Comment by mattporritt** [comment]
Created issue #48 qbank_filter: filter by tag

**Comment by mattporritt** [comment]
Created issue #49 qbank_filter: Filter by date

**Comment by mattporritt** [comment]
@abonaccorso
Are you able to clarify what this statement means? How does the user want to sort the questions:

"She than sorts the questions by discrimination index to make sure she does only include old questions of high quality or newly written ones."

**Comment by abonaccorso** [comment]
@mattporritt the "discrimination index" is one of the statistics Moodle displays for a question. You may find it in the "quiz structure analysis" (quiz statistics). The idea behind is that users are able to filter their questions for specific statistical values
- above a certain value
- below a certain value
- or between two values
it might be a good idea to also have a look at the user stories labeled "Metadata" when implementing the filter: https://docs.google.com/document/d/1JPBTqpCbtdRFTJuX-GIaxKyxtFLoUdPO/edit#heading=h.fsg8o189sc96. Here i specified which meta data each question has - and for all of this meta data filtering should be possible.

**Comment by mattporritt** [comment]
Created issue #51 qbank_filter: Filter by discrimination index

**Comment by abonaccorso** [comment]
Besides _discrimination index_ there are also the following statistics for which one should be able to filter questions

- facility index 
- standard deviation 
- random guess score
- intended weight
- effective weight
- discrimination efficiency

all of them are in %, so the all should be filtrable
- above a certain value
- below a certain value
- between two values

filtering for a specific value makes less sense here, but might be a requirment for other meta data being numbers.
