### ISSUE TITLE
Create tasks: Scenario 1, filter 2

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#28]
Split the following user story in to project tasks:
**Filter 2: Save and reuse filters**
Eva has finalized the exam and asked one of her colleagues to review the exam. She gets the feedback that questions 4 and 16 are outdated. For question 4 the respective learning objective is no longer taught in the course. For question number 16 the respective knowledge is no longer current. As question 4 belongs to topic 1, Eva reruns the filter she used for finding questions for topic 1 and selects another question to replace question 4. Afterwards she tags question 16 as “outdated” and writes a comment that the knowledge is no longer current. She then reruns the filter she used to find question 16 (topic x, learning objective 3) and replaces question 16 by a current question.

**Comment by abonaccorso** [comment]
shall I add respective user stories here? (or at least indicate where you would find them in the document)?

**Comment by mattporritt** [comment]
These should now be individual issues. Anything else will be picked up as we go.
closing.
