### ISSUE TITLE
Create tasks: Scenario 1, filter 3

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#29]
Split the following user story in to project tasks:
**Filter 3: Using filter for creating questions in a shared question bank**
By the discussion he had with his students this morning, lecturer Leon was inspired  for some new questions he might ask his students in one of his formative quizzes. Leon now wants to transform the notes he took into proper questions. He goes to his question bank and filters for the tags “topic X”, learning objective 2”. He quickly scrolls through the questions to see if one of the ideas he had already exists. He then creates his first question. This question automatically adds the tags “topic X” and “learning objective 2”. 
After Leon has saved his first question, he is back in the question bank. The filter he chose priorly (tags “topic X” and “learning objective 2”) still persists. He now creates all his other questions that also have added tags “topic X” and “learning objective 2” automatically.

**Comment by abonaccorso** [comment]
@mattporritt shall I add respective user stories here?

**Comment by mattporritt** [comment]
These should now be individual issues. Anything else will be picked up as we go.
closing.
