### ISSUE TITLE
question versioning - Fix external method submit_tags_forms

### ISSUE THREAD

**Issue by marcghaly** [catalyst/moodle-MDL-70329#293]
Adding a tag does not work. 
See images below.

![Screenshot from 2021-09-03 14-59-48](https://user-images.githubusercontent.com/76186988/132056600-93ea9596-4ea0-40ce-8757-4fc17e222fdc.png)
![Screenshot from 2021-09-03 14-59-33](https://user-images.githubusercontent.com/76186988/132056601-3ee9b3a4-214a-4a49-94e2-c6dc0f2782c6.png)

**Comment by guillogo** [comment]
Hi @marcghaly can you add the steps to get this error please? I couldn't replicate it so far. thank you.

**Comment by marcghaly** [comment]
Hi @guillogo, to replicate navigate to the question bank view, create a question, in the question bank view click ´edit´then ´Manage tags´ and try adding a new tag,
Thank you

**Comment by safatshahin** [comment]
@marcghaly 
As of our conversation, closing the issue as we could not replicate and feels like a branching issue.
