### ISSUE TITLE
Document initial migration steps

### ISSUE THREAD

**Issue by nhoobin** [catalyst/moodle-MDL-70329#3]

**Comment by mattporritt** [comment]
I see this having (at least) two parts.

1. Moodle administrator documentation. So everyone understands the changes that will happen as part of an upgrade to Moodle 4.0. This will need to live in the Moodle wiki and upgrade.txt
2. Developer documentation for those with plugins etc.

**Comment by mattporritt** [comment]
This will also be an evolving piece of work. As a first step that can be done now, is making a start to the Moodle.org docs
