### ISSUE TITLE
Create tasks: Shared question bank 1

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#30]
Split the following into individual project tasks:

**Shared question bank 1: Coordinating an exam with many examiners**
Eva needs to collect questions from several guest lecturers such as Gwendolin who took over a single course day during the term. As Gwendolin is new to Moodle, Eva creates two example questions for Gwendolin. She does that by copying two nice questions into a new category called “examples''. She then sends the link of this category to Gwendolin. 
Eva’s other guest lecturers recycle their questions from last year. In this case Eva profits from the course-independent item-statistics to pick questions based on criteria like item difficulty, discrimination index and tags (e.g. Blooms taxonomy level, learning objectives). Since the exam should, besides having questions of each lecturer, consist of several question types (while other question types may be forbidden), as well as test different competencies and learning objectives, she applies the filter function to have displayed the respective criteria. Using the filter function she appreciates very much the possibility to apply several filters at once (e.g. learning objective AND item statistics AND question type). She can do this either through point & click functionality or by writing simple or complex commands using a predefined syntax. Tags already helped her before, but with the additional option to sort and filter her huge question bank, adding questions to an exam has become a lot easier.

**Comment by abonaccorso** [comment]
@mattporritt shall I add user stories here as well?

**Comment by mattporritt** [comment]
These should now be individual issues. Anything else will be picked up as we go.
closing.
