### ISSUE TITLE
Resolve peer review comments - commit 1

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#327]

**Comment by guillogo** [comment]
Hi @safatshahin This PR will fix Tim's comment for commit # 1 in versioning:

PR: https://github.com/catalyst/moodle-MDL-70329/pull/333
Changes done (in our shared doc): https://docs.google.com/document/d/1djtaOjfUWVRXtyCNbrhaEQ01YooY1ItpURaVxAFDREM/edit
Changes done (if team wants to check): https://etherpad.catalyst.net.nz/commit-1-versioning

About point 5 `Each chunk should be in a separate < 2021092400.01, < 2021092400.02, < 2021092400.03... block`. I have done that in 3 chunks, however we need to change the version number when testing as is using master version right now.

Thank you.
