### ISSUE TITLE
Implement qbank plugin type in question bank structure

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#34]
implement qbank plugin type as a part of question structure, a deep dive task will should include at least the following:
1. Moodle autoloading
2. lib/plugininfo
3. lib/components
4. lib/plugin_manager
5. creating dirs
6. creating base class: qbank.php
7. creating some test plugins as qbank type
8. moodle install with those
9. lib/components.json
10. an so many more

further documentation can be found here: https://docs.google.com/document/d/1W-VZV1XgtQWo0QQytfz536YTiSBOkjSagroc9ZcJDDE/edit#
https://docs.google.com/document/d/1_PcbDOPbcqeiEPtglm2Tsx6YIJypcKOOlAir2lc4D_8/edit#

**Comment by mattporritt** [comment]
Hi Safat.
Thanks for working on this. I've made a PR for this just to track things, it is: #45 

The code looks fine, largely just boilerplate for a new plugin type at this stage. Which is 100% fine.
There are a few things I'll get you to do as part of this:

* [ ] Fix the missing new lines at the end of the new files you've added
* [ ] In `admin/plugins.php` the Question bank plugin section says `qbank` for some reason. See screenshot below
* [ ] Split the `add_question` into a new branch
* [ ] Create a new Moodle tracker for this new plugin type, under the MDL-70329 epic
* [ ] Create a new Moodle tracker for the `add_question` qbank plugin under  under the MDL-70329 epic

**Comment by safatshahin** [comment]
made changes to the code and added the missing strings for qbank type, waiting on the moodle tracker to get ability to add issues in the epic.

**Comment by mattporritt** [comment]
Created the tracker issue: https://tracker.moodle.org/browse/MDL-71525

**Comment by mattporritt** [comment]
@safatshahin can you please retry your tracker access?

**Comment by safatshahin** [comment]
Hi @mattporritt 
checked this morning, same issue, can we move this to done and address this tracker access issue in #8 or a new one?

**Comment by mattporritt** [comment]
@safatshahin ,
see note in: https://github.com/catalyst/moodle-MDL-70329/issues/5#issuecomment-834003185
But essentially we need to make branch: MDL-71516 and move everything into that for this feature

**Comment by safatshahin** [comment]
hi @mattporritt 
branch created: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71516

**Comment by mattporritt** [comment]
I have updated the git branch and diff url in the tracker

**Comment by safatshahin** [comment]
Changed the boilerplate to implement in the modern way moodle following these days.

**Comment by guillogo** [comment]
Hi @safatshahin I've reviewed the PR and posted some comments there. Thank you.

**Comment by mattporritt** [comment]
@safatshahin don't forget to go through the ready for tracker checklist. If you haven't already.

Cheers,
Matt P

**Comment by safatshahin** [comment]
Thanks for the reminder @mattporritt , will do them according to your checklist.

Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Backup and restore functionality has been implemented if required.
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by safatshahin** [comment]
Pr created with the changes #110

**Comment by mattporritt** [comment]
@safatshahin 
I've reviewed and merged the pull request.
This looks read to have the tracker checklist applied. Don't forget to squash the commits.

Cheers

**Comment by mattporritt** [comment]
integrated
