### ISSUE TITLE
Implement qbank type plugins - actions for single questions

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#35]
the following qbank type plugins need to build:
(most of them will be moved from the current classes)
Edit/copy question
Preview question
Delete question
Manage question tags
Export as XML

further documentation can be found here: https://docs.google.com/document/d/1W-VZV1XgtQWo0QQytfz536YTiSBOkjSagroc9ZcJDDE/edit#
https://docs.google.com/document/d/1_PcbDOPbcqeiEPtglm2Tsx6YIJypcKOOlAir2lc4D_8/edit#

**Comment by mattporritt** [comment]
Hi @safatshahin 
Do we still need this as a separate issue? Or has the related work been picked up in other issues?

**Comment by safatshahin** [comment]
Hi @mattporritt 
This has been done in different issues and has been picked up.
This issue can be closed.
Thanks
