### ISSUE TITLE
Behat: qbank_comment - question_comment.feature

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#352]
add another scenario testing if comments added/deleted via quiz activity page are(no longer) visible in the preview (and vice versa)

https://github.com/moodle/moodle/blob/master/question/bank/comment/tests/behat/question_comment.feature

**Comment by marcghaly** [comment]
Hi @mattporritt @safatshahin here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-352
Thank you
