### ISSUE TITLE
"Exception - Class 'quiz_access_manager' not found" error in "need for revision" column

### ISSUE THREAD

**Issue by lucaboesch** [catalyst/moodle-MDL-70329#358]
https://quiz4.catalyst-au.net/question/edit.php?courseid=9 shows this error right now.
<img width="1437" alt="grafik" src="https://user-images.githubusercontent.com/377279/139416796-7d69a4c4-7ac7-458c-b739-3769eaeac946.png">

**Comment by safatshahin** [comment]
Hi @lucaboesch 
Thank you for pointing that here. I have resolved the issue in both the versioning branch and the testsite, please have a look and let me know if the issue still persists.
Thanks
