### ISSUE TITLE
"created by" and "last saved by" in question edit form have the same content

### ISSUE THREAD

**Issue by abonaccorso** [catalyst/moodle-MDL-70329#359]
When I have a look at a specific question version in the question edit form, under "Created/last saved" the two entries "Created by" and "Last saved by" have the same content. Which makes sense as every edit creates a new version. 

![grafik](https://user-images.githubusercontent.com/13217187/139426710-ba11e8db-7492-4668-a3b2-844f455a24bc.png)

The same information is also given at the top of the question edit form

![grafik](https://user-images.githubusercontent.com/13217187/139426836-5cbbafdf-ed69-4f53-83a3-d5becc490e80.png)

So I think we could delete the whole paragraph "Created/Saved".

**Comment by safatshahin** [comment]
Hi @abonaccorso 
I have investigated the issue and it has been resolved in the versioning as we will have just one column created by. I have a tracker to address to the modified by column as Tim suggested we can tailor that column differently.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin do you already have sreenshot of what it looks like when fixed? I have some troubles imagining what it is like

**Comment by marcghaly** [comment]
Hi @safatshahin, as stated above by @abonaccorso I deleted the last paragraph "Created / last saved", can you please confirm that is what you want ? 
Here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-359

Thank you

**Comment by marcghaly** [comment]
Hi @safatshahin, as discussed last paragraph "Created / last saved" was removed.

https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-359

Thank you.

**Comment by safatshahin** [comment]
@marcghaly thanks for working in this.
before I integrated it to the versioning branch, can you please confirm the behat tests are passing?
thanks

**Comment by marcghaly** [comment]
Hi @safatshahin, `@mod_quiz` and `@core_question` are passing.

Thank you

**Comment by safatshahin** [comment]
Hi @abonaccorso 
The testsite is updated with this change. Please let me know if I can help with any other information.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin looks good. Thanks!
