### ISSUE TITLE
Implement qbank type plugins - multiple question feature

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#36]
Add question (shows type chooser before redirecting to the Edit plugin)
Manage categories
Import questions
Export questions
Bulk move
Bulk delete

further documentation can be found here: https://docs.google.com/document/d/1W-VZV1XgtQWo0QQytfz536YTiSBOkjSagroc9ZcJDDE/edit#

**Comment by mattporritt** [comment]
As work has already started on the `add_question` plugin it'll be split into a new issue

**Comment by mattporritt** [comment]
Hi @safatshahin
Do we still need this as a separate issue? Or has the related work been picked up in other issues?

**Comment by safatshahin** [comment]
Hi @mattporritt 
We have different issues for each of them now, this issue can be closed.
Thanks
