### ISSUE TITLE
Move dependencies to quiz and random from qbank_preview

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#362]
At the moment, to make the preview work with the preview question, it relies on some variables from quiz and also makes those rendering inside the qbank_preview plugin.
Move those dependencies from qbank_preview, create a method in the helper, get the id of the question from that method, and pass that id to get the preview of the question. That way qbank_preview is independent.
Keep all the changes in one commit so I can cherry-pick and squash to the appropriate one.

**Comment by marcghaly** [comment]
Hi @safatshahin, here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-362/363/360 as discussed I removed the preview for random.
Thank you
