### ISSUE TITLE
Behat enhancement - mod_quiz

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#363]
I can see where you are going with the new 'I click on "Configure question" "link" in the "2" list item' - but that is not exacty human-readable. There is no "2" list item on the page. A better way to do this is to define a custom selector, as in https://docs.moodle.org/dev/Writing_acceptance_tests#Custom_selectors_.28..._in_the_.22....22_.22....22.29. Then you can say 'I click on the "Configure question" "link" in the "2" "mod_quiz > Edit slot"

The point is to separate what appears in the .feature file, which should be a beautifully human-readable as possible, from the implementation which makes that work. Internally in Behat essentially everything ends up being a complicated XPath sent to Selenium / WebDriver. So, yes, to implement the selector I suggested, you will have to work out some compicated XPath. That's what you have to do. Obviosuly, in my example, when I say 'Slot 2' I mean the second visible slot in the HTML, not the slotid from the database - that would not be human-readable.)

**Comment by marcghaly** [comment]
Hi @safatshahin, here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-362/363/360
Thank you
