### ISSUE TITLE
Quiz behat change for the original scenarios

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#366]
This change to the Behat is just wrong: https://github.com/catalyst/moodle-MDL-70329/compare/master_MDL-70329-base-peerreview...master_MDL-71696-versioning-peerreview#diff-8d4b0c6384809c8039bdfcdde939f4b34631a70ec5ed38c49524479dc3b3411bL122 Read the setup.
Behat step i_should_see_or should not exist. (If it did, which it does not, I would not belong in mod quiz.)
Scenario: Selecting approriate question versions is not a great Behat scenario. Can you at least break it up with some blank lines and comments, to give a higher-level overview of what is going on.

**Comment by marcghaly** [comment]
Hi @safatshahin, here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-peerreview-366

Thank you
