### ISSUE TITLE
Question preview script changes

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#367]
question/bank/previewquestion/preview.php - it is a bit messy having required_param $id and optional_param $version. Why not just always make sure that the correct id is pased to this scritpt in the $id parameter.

**Comment by marcghaly** [comment]
Hi @safatshahin, here is the work for:
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-peerreview-367

Thank you
