### ISSUE TITLE
Question versioning behat tests

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#369]
Scenario: Report works when there are no attempts  -- string change, failing for string

Scenario: Duplicating a previously created question -- idnumber issue

**Comment by abonaccorso** [comment]
Hi @safatshahin could we maybe add a behat for deleting question versions? The scenario would look like: I have version 1 - 7 and delete version 2 and 5 - so there should remain versions 1, 3, 4, 6 and 7 visible - and 2 and 5 should appear once I tick "Show also hidden questions". I think this is a very important requirement of the versioning.

Sidemark: I did not check all the behat tests for versioning yet, so maybe you already wrote that one. In this case: just ignore me :)

**Comment by safatshahin** [comment]
Hi @abonaccorso 
That totally sounds like something to go in the history plugin where it will use bulk action or the delete action to delete some questions and will check what is happening. I will create a git issue for that to implement in the history plugin.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin thanks for your quick response. I am always confusing versioning and history plugin - sorry for that. And thanks for creating a new issue on the behat test proposed by me!
