### ISSUE TITLE
Resolve the CI issues from core_backup

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#397]
https://integration.moodle.org/job/Precheck%20remote%20branch/115136/artifact/work/smurf.html#savepoint

This mentions come ci bot issues from core backup.
Leave the changes in one commit so I can squash that to the appropriate commit.

**Comment by guillogo** [comment]
Hi @safatshahin 

This is the PR to fix CI issues from core_backup: https://github.com/catalyst/moodle-MDL-70329/pull/401
Commit to cherry-pick: https://github.com/catalyst/moodle-MDL-70329/pull/401/commits/ffd0d47c92be79ec1cbf7d470d4031a4a36d48f5

Thank you.
