### ISSUE TITLE
Resolve the CI issues from lib

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#398]
https://integration.moodle.org/job/Precheck%20remote%20branch/115136/artifact/work/smurf.html#savepoint

leave them in one commit so that I can squash that in the appropriate commit.

**Comment by guillogo** [comment]
Hi @safatshahin 

To fix it please  cherry-pick this commit: https://github.com/catalyst/moodle-MDL-70329/pull/401/commits/ef2b549bca904372a9c397e48b717c0ff28796cc

Thank you,
**Guillermo**
