### ISSUE TITLE
Update question status js

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#403]
According to integrator's comment, the status js can be updated:
https://tracker.moodle.org/browse/MDL-71696?focusedCommentId=890059&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-890059

Please use the following branch:
https://github.com/catalyst/moodle-MDL-70329/commits/master_MDL-71696-versioning-integration

**Comment by guillogo** [comment]
Hi @safatshahin this is the PR: https://github.com/catalyst/moodle-MDL-70329/pull/405 to fix Andrew L comments related with status js. Thank you.
