### ISSUE TITLE
Update quiz slot js

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#404]
https://tracker.moodle.org/browse/MDL-71696?focusedCommentId=890150&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-890150

**Comment by guillogo** [comment]
Hi @safatshahin this PR has the changes requested by AndrewL for question slot js -> https://github.com/catalyst/moodle-MDL-70329/pull/406 thank you.
