### ISSUE TITLE
mod_bank: make a "core" plugin type

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#46]
The current mod_qbank is being shown as an additional plugin in the plugin overview page.
We need to change it so it's not marked as additional as this will be a core plugin.

![image](https://user-images.githubusercontent.com/7369127/116767322-d61ab400-aa72-11eb-8b45-dfcc0c8ed396.png)

**Comment by safatshahin** [comment]
hi @mattporritt 
it was a tiny change in the plugin_manager, didnt create a new branch for this one, added it as a part of #34

**Comment by mattporritt** [comment]
hi @safatshahin I've commented on the pull request

**Comment by mattporritt** [comment]
@safatshahin PR merged

**Comment by safatshahin** [comment]
@mattporritt moving it to done
