### ISSUE TITLE
addquestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#50]
named this without _ to follow moodle guideline

**Comment by safatshahin** [comment]
Repo for this issue: 
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71378-%2350

**Comment by mattporritt** [comment]
Created tracker issue https://tracker.moodle.org/browse/MDL-71525

**Comment by safatshahin** [comment]
this feature is implemented in the editquestion plugin

**Comment by safatshahin** [comment]
PR #83

**Comment by guillogo** [comment]
Hi @safatshahin peer review done, just a  couple of little comments in the PR. Thank you.

**Comment by mattporritt** [comment]
@safatshahin and @guillogo I've removed the individual tracker for this. This PR will need to be merged into the MDL-71574 branch along with issue #54 and issue #81

**Comment by guillogo** [comment]
Hi @safatshahin 

Tested and approved issues:

- https://github.com/catalyst/moodle-MDL-70329/issues/54
- https://github.com/catalyst/moodle-MDL-70329/issues/50
- https://github.com/catalyst/moodle-MDL-70329/issues/81

TODO:

1. Merge.
2. Add the ready for tracker check list.

Thank you.

**Comment by safatshahin** [comment]
checklist added in #54

**Comment by safatshahin** [comment]
implemented as a part of #54 
issue can be closed
