### ISSUE TITLE
editquestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#54]

**Comment by mattporritt** [comment]
Hi @safatshahin 
Can you make the branch: MDL-71574 and add this code to it?
I've also created tracker: MDL-71574 for this feature.

**Comment by safatshahin** [comment]
hi @mattporritt 
did the branching as you asked, PR #83

**Comment by mattporritt** [comment]
@safatshahin and @guillogo This branch MDL-71574 will also be used for issue #50 and issue #81

**Comment by guillogo** [comment]
Hi @safatshahin 

Tested and approved issues:

- https://github.com/catalyst/moodle-MDL-70329/issues/54
- https://github.com/catalyst/moodle-MDL-70329/issues/50
- https://github.com/catalyst/moodle-MDL-70329/issues/81

TODO:

1. Merge.
2. Add the ready for tracker check list.

Thank you.

**Comment by safatshahin** [comment]
Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Backup and restore functionality has been implemented if required.
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by safatshahin** [comment]
Changes done after the review, waiting for final peer review done.

**Comment by guillogo** [comment]
Hi @safatshahin changes approved. The PR was merged. thank you.

**Comment by safatshahin** [comment]
Hi @mattporritt 
This issue is ready for tracker, can you please update the tracker?
Thanks

**Comment by mattporritt** [comment]
tracker updated

**Comment by mattporritt** [comment]
integrated
