### ISSUE TITLE
previewquestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#55]

**Comment by mattporritt** [comment]
I've created tracker issue MDL-71614 for this plugin.
I've also pre-emptively added the branch and git diff urls to the tracker

**Comment by safatshahin** [comment]
Added the branches, PR #93

**Comment by safatshahin** [comment]
Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Backup and restore functionality has been implemented if required.
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by mattporritt** [comment]
@safatshahin tracker updated

**Comment by guillogo** [comment]
The phase 2 has been approved and merged. https://github.com/catalyst/moodle-MDL-70329/pull/204

**Comment by mattporritt** [comment]
closing, issue has been integrated
