### ISSUE TITLE
importquestions - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#56]
import question is a feature in questionbank which will need to be implemented as a plugin.

further documentation can be found here: https://docs.google.com/document/d/1W-VZV1XgtQWo0QQytfz536YTiSBOkjSagroc9ZcJDDE/edit#
https://docs.google.com/document/d/1_PcbDOPbcqeiEPtglm2Tsx6YIJypcKOOlAir2lc4D_8/edit#

**Comment by mattporritt** [comment]
The aim here is to make a qbank_importquestions plugin.
This plugin will replicate the current core functionality that allows the importing of questions, and "move" it into this plugin

This will be a similar implementation to issue #57 that handles question exporting

**Comment by mattporritt** [comment]
Hi Marc,
Start by creating the "shell" code for the plugin. With basic file structure, language strings etc. 
Then move across the existing logic from core.

The work that was done in #57 should for a good base for you to copy from.

Cheers

**Comment by marcghaly** [comment]
Currently reading the work done in [#57 ](https://github.com/catalyst/moodle-MDL-70329/issues/57) to have a better understanding

**Comment by mattporritt** [comment]
I've added the git branch and diff urls to the tracker

**Comment by guillogo** [comment]
Hi @marcghaly 

It's fine to use the same old PR https://github.com/catalyst/moodle-MDL-70329/pull/75 no need to create a new one. 

To do:

1. Close new PR created: https://github.com/catalyst/moodle-MDL-70329/pull/89.
2. Revert commit https://github.com/catalyst/moodle-MDL-70329/pull/75/commits/5b027762c5766b7e4315797948b976c332aacae3
3. Check review comments in PR https://github.com/catalyst/moodle-MDL-70329/pull/75. 

Thank you.

**Comment by guillogo** [comment]
Hi @marcghaly I'll review the PR shortly after the last changes. Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo @marcghaly 
Please rebase it against the latest 71516. thanks

**Comment by guillogo** [comment]
Hi @marcghaly review done. Can you have a look please? Basically:

1. rebase
2. call new function to validate if a plugin is enable or not.

Thank you.

**Comment by marcghaly** [comment]
Hi @guillogo I did the changes in the PR https://github.com/catalyst/moodle-MDL-70329/pull/141

**Comment by guillogo** [comment]
Hi @marcghaly 

The PR has been merged. Now, can you please:

1. Add the check list.
2. Squash the commits in `master_MDL-71608`

Also, I've rebased against MDL-71516 so no need to do it again.

Thank you.

**Comment by marcghaly** [comment]
Adding for tracker checklist.

For Tracker checklist:

- [ ]  Issue is rebased against current master branch or appropriate parent branch
- [ ]  Backup and restore functionality has been implemented if required.
- [ ]  Unit tests have been ported from original code and are passing
- [ ]  Unit tests have been written and are passing
- [ ]  Behat tests have been ported from original code and are passing
- [ ]  Behat tests have been written (if needed) and are passing
- [ ]  Someone on the team has done an initial peer review of this
- [ ]  Tracker issue description is up to date and accurate
- [ ]  Tracker test instructions are up to date and accurate
- [ ]  Tracker diff and pull url are up to date and accurate

**Comment by marcghaly** [comment]
@guillogo 

- Checklist added
- Testing instructions and tracker up to date
- Commits squashed and added in `master_MDL-71608`

**Comment by guillogo** [comment]
Hi, the phpdoc errors (docs) https://tracker.moodle.org/browse/MDL-71608?focusedCommentId=864610&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-864610 that are not false positive for this plugin have been fixed for this plugin.

**Comment by guillogo** [comment]
Behat test:
@mod_quiz: OK
@core_question: OK

**Comment by mattporritt** [comment]
integrated
