### ISSUE TITLE
exportquestions - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#57]

**Comment by guillogo** [comment]
Hi,

This is the PR for the new plugin `export` https://github.com/catalyst/moodle-MDL-70329/pull/67

1. Plugin created.
2. Old core question bank works using the new plugin.

Thank you.

**Comment by mattporritt** [comment]
hi @guillogo ,
Can you make the branch: MDL-71573 and add this code to it?
I've also created tracker: MDL-71573 for this feature.

**Comment by mattporritt** [comment]
I have updated the tracker with the git branch and diff urls

**Comment by guillogo** [comment]
Thank you @safatshahin for reviewing the PR: https://github.com/catalyst/moodle-MDL-70329/pull/78 I've done the changes. Could you take a look again please?

**Comment by safatshahin** [comment]
thanks @guillogo 
almost done, just a little change, then we are all good to go.

**Comment by guillogo** [comment]
Thank you @safatshahin done now :)

**Comment by guillogo** [comment]
For qbank_exportquestions

1. code style in refactored files fixed.
2. provider class added.
3. All review comments done.
4. rebased.

**Comment by guillogo** [comment]
Hi @safatshahin this in now ready for reviewing. PR: https://github.com/catalyst/moodle-MDL-70329/pull/145 Thank you.

**Comment by safatshahin** [comment]
Hi @guillogo 
Thank you for working in this. Review done, i have rebased it with the latest base, just need to squash the commits and ready for tracker.

**Comment by guillogo** [comment]
Adding for tracker checklist.

For Tracker checklist:

- [ ]  Issue is rebased against current master branch or appropriate parent branch
- [ ]  Issue commits have been squashed and have correct commit message
- [ ]  Backup and restore functionality has been implemented if required.
- [ ]  Unit tests have been ported from original code and are passing
- [ ]  Unit tests have been written and are passing
- [ ]  Behat tests have been ported from original code and are passing
- [ ]  Behat tests have been written (if needed) and are passing
- [ ]  Someone on the team has done an initial peer review of this
- [ ]  Tracker issue description is up to date and accurate
- [ ]  Tracker test instructions are up to date and accurate
- [ ]  Tracker diff and pull url are up to date and accurate

Tracker: https://tracker.moodle.org/browse/MDL-71573

**Comment by guillogo** [comment]
Hi @mattporritt this ready for tracker now, can you please change the status to waiting for peer review for me? thank you. https://tracker.moodle.org/browse/MDL-71573

**Comment by mattporritt** [comment]
@guillogo tracker has been updated

**Comment by guillogo** [comment]
Behat test:
@mod_quiz: OK
@core_question: OK

**Comment by mattporritt** [comment]
integrated
