### ISSUE TITLE
managecategories - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#58]

**Comment by abonaccorso** [comment]
Hi @safatshahin do I understand correctly that you will implement the functionalities for managecategories as already existing in Moodle 3.9?
 
So as a user I will be able to

- create categories (subcategories and so on)
- move categories using the arrow icons (<--, -->, arrow up, arrow down)
- delete categories using the dustbin icon

I am asking because there are ideas to improve managecategories but they are low priority and might be implemented by an external developer contributing development time.

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for your detailed explanation. As a part of the questionbank redesign, we will be implementing every feature as a plugin. As a part of that, the current category management will be implemented as an individual plugin but will work exactly same as the current feature, its more like a refactoring rather than enhancementm this ticket is related to that.
I hope i could explain it properly, please do let me know if you have any more questions.
Thanks

**Comment by abonaccorso** [comment]
Hi @safatshahin 

Many thanks for clarifying that this is just about implementing existing features in the new plugin - not about adding additional functionality. That was all I wanted to know.

**Comment by guillogo** [comment]
Hi,

The plugin qbank_managecategories has been created.
Tracker: https://tracker.moodle.org/browse/MDL-71585 ( @mattporritt could you please add it to the epic?)
PR: https://github.com/catalyst/moodle-MDL-70329/pull/72

Thank you,
Guillermo.

**Comment by mattporritt** [comment]
I have linked the tracker for this to the quiz epic. I have also added the branch at git diff urls to the tracker

**Comment by guillogo** [comment]
For qbank_managecategories

1. code style in refactored files fixed.
2. provider class added.
3. All review comments done.
4. rebased.

Thank you.

**Comment by guillogo** [comment]
Hi @safatshahin the unit test have been moved, can you have a look please to https://github.com/catalyst/moodle-MDL-70329/pull/79 ? thank you.

**Comment by guillogo** [comment]
Hi @safatshahin can you have a look please to this PR: https://github.com/catalyst/moodle-MDL-70329/pull/163

1. Manage categories refactor.
2. Move unit test.
3. Add plugin navigation.

The branch was rebased with the last changes in master_MDL-71516

Thank you.

**Comment by safatshahin** [comment]
This plugin build is done, the next phase of this build for UI enhancement is in progress in #148

**Comment by guillogo** [comment]
the phpdoc errors https://tracker.moodle.org/browse/MDL-71585?focusedCommentId=864612&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-864612 that are not false positive for this plugin have been fixed for this plugin.

**Comment by guillogo** [comment]
Behat test:
@mod_quiz: OK
@core_question: 51 scenarios (49 passed, 2 failed) - Fixed the 2 scenarios now.

**Comment by mattporritt** [comment]
closing as this has now been integrated into core
