### ISSUE TITLE
viewcreator - qbank plugin type

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#59]
qbank plugin to view the creator of the question bank
important note: this plugin is progress as a test transmission to check how moodle behaves with plugins extending base classes inside the qbank and how view base class pulls the available plugins and populates the columns according to that.
success of this plugin will help the next builds to follow the same guideline for all the view plugins for the base view of the table.

**Comment by mattporritt** [comment]
I've created tracker issue MDL-71613 for this plugin.
I've also pre-emptively added the branch and git diff urls to the tracker

**Comment by safatshahin** [comment]
@marcghaly 
Assigning you this one, this is plugin build for qbank_

You will need to create a branch ahead of:
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71516

and create the plugin which will render the created by and last modified by column.

Please use the following branches as a reference:
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71576-65
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71577-64

**Comment by marcghaly** [comment]
PR was created for this issue: https://github.com/catalyst/moodle-MDL-70329/pull/130

**Comment by mattporritt** [comment]
@safatshahin you likley best placed to review PR #130

**Comment by safatshahin** [comment]
sure @mattporritt reviewing it now.
thanks

**Comment by safatshahin** [comment]
Hi @marcghaly 
Thank you for working on this issue.
I have done the review for PR #130 
There are some changes required from the branching, you can do the changes and then we can rename the branches if that is easier.
Thanks

**Comment by marcghaly** [comment]
Hi @safatshahin, I fixed code and branching issues you mentioned, here is the new PR: https://github.com/catalyst/moodle-MDL-70329/pull/136

Thank you

**Comment by guillogo** [comment]
Hi @marcghaly 

The PR was merged. Now you can start adding the Ready for tracker checklist and squashing the commits. (All should be in 1 commit. For more info: https://docs.moodle.org/dev/Commit_cheat_sheet).

Thank you.

**Comment by safatshahin** [comment]
Hi @mattporritt  @guillogo 
Looking at the wireframes and also thinking about the future if this plugin, will it be better to rename it to qbank_history or qbank_version  or anything more specific? I can clearly see this plugin will change very soon and the name viewcreator wont match those changes. Any thoughts?
Thanks

**Comment by marcghaly** [comment]
Adding for tracker checklist.

For Tracker checklist:

- [ ]  Issue is rebased against current master branch or appropriate parent branch
- [ ]  Backup and restore functionality has been implemented if required.
- [ ]  Unit tests have been ported from original code and are passing
- [ ]  Unit tests have been written and are passing
- [ ]  Behat tests have been ported from original code and are passing
- [ ]  Behat tests have been written (if needed) and are passing
- [ ]  Someone on the team has done an initial peer review of this
- [ ]  Tracker issue description is up to date and accurate
- [ ]  Tracker test instructions are up to date and accurate
- [ ]  Tracker diff and pull url are up to date and accurate

**Comment by marcghaly** [comment]
@guillogo @mattporritt Added the testing instructions as comment, unsure how to add under the `Testing Instructions` pane.

**Comment by mattporritt** [comment]
> Hi @marcghaly
> Thank you for working on this issue.
> I have done the review for PR #130
> There are some changes required from the branching, you can do the changes and then we can rename the branches if that is easier.
> Thanks

Lets just leave it as is no, we can always change later
