### ISSUE TITLE
viewcheckbox - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#60]

**Comment by mattporritt** [comment]
I have added the git hub branches and diff url to the tracker

**Comment by guillogo** [comment]
> Hi @mattporritt
> Code pushed to: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71579-60
> PR: #73

Hi, merged worked as expected.

**Comment by mattporritt** [comment]
Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by safatshahin** [comment]
Integration ready PR: #104

**Comment by guillogo** [comment]
Hi @safatshahin ,
Integration ready stage tested and working good. Also,

1. unit test passing.
2. codechecker happy.

Thank you,
**Guillermo**

**Comment by mattporritt** [comment]
Hi @safatshahin and @guillogo ,
Apologies if you are still going though this. I've just had a quick look and the following things have jumped out to me:

* [ ] Commits have been squashed with compliant commit message
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by safatshahin** [comment]
Thanks a lot for the list @mattporritt 
will do follow the list before moving to ready for tracker for all the branches.

**Comment by safatshahin** [comment]
plugin added to to core, issue and tracker can be closed.
