### ISSUE TITLE
Workflow: Adding questions to quiz

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#61]
Currently for a new quiz in a new course, when a user wants to add a question to a quiz and they click the "add" link:
* The first option is to add a question "directly" to the quiz
* The second option is to add a question from a question bank

If the user chooses to add a question from the question bank, the question bank chosen by default is the course question bank. The course question bank is automatically created when the course is created.

Is this the workflow we want to keep going forward?

Some additional information/thoughts:
* Quizzes will still have their inherit question bank
* Do we want to create a question bank activity when a new course is created?
* When a user chooses to add a question from a question bank and they do not have access to any question banks, should they be guided through to create a new questionabnk?

I'm sure there are more considerations than this.

**Comment by mattporritt** [comment]
Hi @abonaccorso I'll leave this with you to follow up

**Comment by abonaccorso** [comment]
related question: what happens in this case?

1. teacher adds question directly to quiz --> question is saved in quiz specific question bank
2. teacher wants to change question (before first attempt was started)
3. teacher edits the question --> new question version is created in quiz specific question bank

--> is the quiz automatically updated with the new question version? or does the teacher have to choose this? is this depending on the decision to include "latest version" or "specific version x" of the question?

**Comment by abonaccorso** [comment]
from this mornings discussion with Luca, Matt, Safat and Guillermo: 
- creating a plain question bank when creating a new course is not liked very much as an idea
- creating a course level (not quiz level) question bank when a user starts adding questions to a quiz might be a good way. Might solve the problem of people not finding their questions anymore and it would solve the the problem of how to get the questions out of the quiz level question bank into a new, shared question bank
- we will propose the way we go to the bigger community - and change in case of broad opposition
- Antonia will write a rough idea down until the 8th of June

**Comment by abonaccorso** [comment]
Hi @lucaboesch, @timhunt, @mattporritt, @brendanheywood, @safatshahin, and @guillogo I worte a first draft for the process how to add questions to a quiz, including some ideas on when to create question banks and where to put them after the first migration from a latter Moodle version to Moodle 4.0. You may find it here https://docs.google.com/document/d/10v71tjuDdgq6eApA-hGU6-inGCUbcsDF/edit. We will discuss it tomorrow anyway

**Comment by abonaccorso** [comment]
I updated https://docs.google.com/document/d/10v71tjuDdgq6eApA-hGU6-inGCUbcsDF/edit# according to this mornings discussion. @lucaboesch, @timhunt could someone please review? As now, it is ready for wire frames from my point of view @lucaboesch
