### ISSUE TITLE
viewquestiontype - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#64]

**Comment by mattporritt** [comment]
Hi @safatshahin
Can you make the branch: MDL-71577 and add this code to it?
I've also created tracker: MDL-71577 for this feature.

**Comment by safatshahin** [comment]
Hi @mattporritt 
Branching done as you asked, please check the PR #74

**Comment by mattporritt** [comment]
I've updated the tracker with git branch and diff urls

**Comment by safatshahin** [comment]
Integration ready PR #105

**Comment by safatshahin** [comment]
Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Backup and restore functionality has been implemented if required.
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by guillogo** [comment]
hi @safatshahin review done: https://github.com/catalyst/moodle-MDL-70329/pull/122#issuecomment-851916117 thank you.

**Comment by guillogo** [comment]
Approved and merged.
