### ISSUE TITLE
viewquestiontext - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#68]

**Comment by mattporritt** [comment]
Hi @safatshahin 
Can you make the branch: MDL-71575 and add this code to it?
I've also created tracker: MDL-71575 for this feature.

**Comment by safatshahin** [comment]
Hi @mattporritt 
Did the branching as you asked. Please check the PR #77

**Comment by mattporritt** [comment]
I have added the branch and git diff url to the tracker

**Comment by guillogo** [comment]
> Hi @mattporritt
> Did the branching as you asked. Please check the PR #77

Hi, merged worked as expected.

**Comment by mattporritt** [comment]
Adding for tracker checklist.

For Tracker checklist:
* [ ] Issue is rebased against current master branch or appropriate parent branch
* [ ] Unit tests have been ported from original code and are passing
* [ ] Unit tests have been written and are passing
* [ ] Behat tests have been ported from original code and are passing
* [ ] Behat tests have been written (if needed) and are passing
* [ ] Someone on the team has done an initial peer review of this
* [ ] Tracker issue description is up to date and accurate
* [ ] Tracker test instructions are up to date and accurate
* [ ] Tracker diff and pull url are up to date and accurate

**Comment by guillogo** [comment]
Hi @safatshahin approved and merged. Thank you.

**Comment by mattporritt** [comment]
@safatshahin I've updated the tracker
