### ISSUE TITLE
Provide access to the project board to the project team

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-MDL-70329#7]
- [x] @abonaccorso
- [x] @tkorner
- [x]  @timhunt 
- [x] @lucaboesch

**Comment by lucaboesch** [comment]
@dmitriim Antonias account is called @abonaccorso

**Comment by lucaboesch** [comment]
@dmitriim Thomas' account is called @tkorner

**Comment by mattporritt** [comment]
This should all be done.
Have followed up with the team to confirm.
