### ISSUE TITLE
deletequestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#82]

**Comment by mattporritt** [comment]
I've created tracker issue MDL-71615 for this plugin.
I've also pre-emptively added the branch and git diff urls to the tracker

**Comment by mattporritt** [comment]
Based on recent meeting, the following was discussed:
    - we don't want to have versions still in use to be deleted (in order no to have broken quizzes with missing questions)
    - what happens to aliasis in other question banks?
    - would it be possible to support the deletion of question geving users the information they need to follow the questions and delete attempts/quizzes --> and then quizzes
    - @abonaccorso will write down a rough thought until the 16th June and we will then discuss and take further decisions

**Comment by mattporritt** [comment]
Due date: 16th June

**Comment by safatshahin** [comment]
Build and initial review done, need to add the function call for plugin enable/disable and minor review changes.

**Comment by guillogo** [comment]
Hi @safatshahin the changes have been approved and merged. Thank you.

**Comment by safatshahin** [comment]
Hi @mattporritt 
This issue is ready for tracker, can you please update the tracker?
Thanks

**Comment by mattporritt** [comment]
Tracker updated

**Comment by abonaccorso** [comment]
missed the deadline by far due to contributor meetings and kick-off meetings and other things, that were discussed instead

**Comment by mattporritt** [comment]
integrated
