### ISSUE TITLE
viewmodifier - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#84]

**Comment by mattporritt** [comment]
@safatshahin would it make sense to include this functionality with the view creator plugin (issue #59 )?
As they are both related to users that have made changes to the question?

**Comment by safatshahin** [comment]
hi @mattporritt 
it will require some changes to the qbank plugin loader in the view base, currently it accepts one class for one base element, like for column, it will accept one class, so that i can do all the other required stuffs in other classes and name the entrypoint class as pluginname_column so that only this class gets added in the loader and all the others are not loaded as they are working in the background of the entrypoint class. 
If we want to support the use of multiple entrypoints for one element, then we need to change this mechanism. Please let me know if you want me to change the loader for that.

**Comment by mattporritt** [comment]
@safatshahin Thanks for the extra info. Let's leave it as is for now.
I was only enquiring to see if we could cut down on some boilerplate. But at the moment it seems like more trouble than it's worth.
Cheers

**Comment by safatshahin** [comment]
Hi @mattporritt 
As a part of the changes to the boilerplate, the entrypoint now accepts unlimited number of columns from each plugins, means we can do it in one plugin now, please let me know if you want me to implement them in one plugin now.
thanks

**Comment by mattporritt** [comment]
@safatshahin if we can put this into one plugin I think that makes sense.
Lets use this one, as the creator of a question is the first modifier

Cheers

**Comment by safatshahin** [comment]
the issue can be closed.
