### ISSUE TITLE
exporttoxml - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#85]

**Comment by mattporritt** [comment]
@safatshahin I've created the tracker MDL-71639 for this plugin

**Comment by safatshahin** [comment]
Build and initial review done, need some minor changes after the review.

**Comment by guillogo** [comment]
Hi @safatshahin the changes have been approved and merged. Thank you.

**Comment by safatshahin** [comment]
Hi @mattporritt 
This issue is ready for tracker, can you please update the tracker?
Thanks

**Comment by mattporritt** [comment]
tracker updated

**Comment by mattporritt** [comment]
closing as tracker is now integrated
