### ISSUE TITLE
tagquestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#86]

**Comment by mattporritt** [comment]
I've created tracker MDL-71641 for this issue.
When this issue gets started, please create branch MDL-71641 and and make pull requests against that

**Comment by safatshahin** [comment]
Currently in review.

**Comment by guillogo** [comment]
Hi @safatshahin PR merged. It's ready for the check list. Thank you.

**Comment by safatshahin** [comment]
Hi @mattporritt 
this one is ready for tracker.
thanks

**Comment by mattporritt** [comment]
tracker updated

**Comment by mattporritt** [comment]
closing issue as it is now integrated
