### ISSUE TITLE
Upgrade: Migrate questions to new Question banks

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#92]
Once issues #90 and #91 have been implemented we need to migrate all the questions from the "old" question banks to the "new" mod_qbank instances.

We need to:
~~* [ ] Convert all existing questions to "versioned" questions~~
* [x] Migrate all existing questions from their category question banks to the new mod_qbank instances
* [x] Migrate all existing questions from their course question banks to the new mod_qbank instances

NOTE: This issue may be blocked by, #21 As we the versioning of questions is reliant on this

**Comment by mattporritt** [comment]
I've removed `Convert all questions to "versioned questions` from this issue. We will tackle that as part of issue #101

**Comment by guillogo** [comment]
Hi,
This PR: https://github.com/catalyst/moodle-MDL-70329/pull/135 will perform the migration.

As the new tables are not in the schema already, the migration will be basically change the contextid in question_categories to point to the new mod_qbank created.

Thank you.

**Comment by mattporritt** [comment]
@guillogo I've approved and merged the PR, we may need to optimise this in the future, but we'll see how it goes

**Comment by guillogo** [comment]
Hi @safatshahin 

I've create this PR https://github.com/catalyst/moodle-MDL-70329/pull/166 to improve the question_categories using existing function  `question_move_category_to_context`. Can you have a look please?

Thank you.

**Comment by guillogo** [comment]
Hi, this one was already merge. Thank you @safatshahin. Closing this now.
