### ISSUE TITLE
Creating a base for question bank view

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#99]
Question bank view is currently rendered via the view base. That base loads all the plugins, gets all the column classes which extending different base classes. So at the moment, the following part of question view is dynamic, and any developer can create a qbank plugin, by extending column base or the action base to add a column or add an action icon.

![Screenshot 2021-05-20 15:21:38](https://user-images.githubusercontent.com/55496911/118923610-28b70400-b97f-11eb-9de8-e2e7dbe066f3.png)

On the other hand, if we look at this area, where is will have the filters, search options, preference selections (like view question text), or maybe a custom button like add a new question, this area still pretty static.

![Screenshot 2021-05-20 15:23:46](https://user-images.githubusercontent.com/55496911/118923849-8f3c2200-b97f-11eb-9787-4bb8f5a695d7.png)

even the area for bulk actions to move and delete questions in bulk.

That means, as a developer, if i have something which needs a preference selection, or needs a button, i can't do that as only half of the page is dynamic. 

My idea is:
Re do the view base class for this view and divide the entire view of the question bank view in 5 different parts:
1. The filtering, where the view base will load all the plugin extending the filterbase, and populate the filer plugins in the page. This will also include the search options (maybe).
2. The preference, which will include the preference specified by the plugin, and that preference and the content of the preference will be defined from the child class of any column base, i did it in the viewquestiontext to get a flavour of it. Finally view base will load all the preferences from all the child columns.
3. Custom buttons, any base class has a custom button required, will have custom button to yes from the child class.
4. The columns and action buttons, which is already doing it from the view base.
5. the bulk actions, any plugin has a bulk action, like extending the bulk action base and view base loads the bulk action (it will be a bit tricky to make it this dynamic).

All these 5 points will be loaded in the view base as soon as the base class is called.

**Comment by mattporritt** [comment]
Hi @safatshahin 
It might be worth reviewing the screenshots in the tracker MDL-70329 as the presentation of this data is going to change and this may effect your thinking here.
Related to the new new designs it would also be worth thinking about how much of this absolutely needs to be done "now" and what can wait until we start implementing the new functionality.

Finally, it does feel like the displaying of the information may to be too tightly coupled to the underlying logic.  Plugins being able to nominate what they provide in terms of filtering, actions etc. should be quite separate from the way they are displayed. For example a plugin should be able to nominate that it can export a question as CSV, and provide the logic to do that, as well as the information it needs to complete that action. How this is displayed to the user should be out of the plugins scope (in most cases).

Cheers,
MattP

**Comment by safatshahin** [comment]
Thanks for the clarification matt. I think the view is going in the right direction and the view is changing with added plugins. Closing this issue.
